//
//  GuestListPresenter.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GuestListPresentationLogic {
    func presentGuests(response: GuestList.FetchGuests.Response)
}

class GuestListPresenter: GuestListPresentationLogic {
    weak var viewController: GuestListDisplayLogic?
    
    // MARK: Presentation Logic
    
    
    func presentGuests(response: GuestList.FetchGuests.Response) {
        
    }
}
