//
//  GuestListWorker.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models
import DataSource

protocol GuestListWorkerProtocol {
    func fetchGuests() async throws -> [Guest]
}

class GuestListWorker: GuestListWorkerProtocol {
    
    private let guestListDataSource: GuestListDataSourceProtocol
    
    init(guestListDataSource: GuestListDataSourceProtocol = GuestListDataSource()) {
        self.guestListDataSource = guestListDataSource
    }
    
    func fetchGuests() async throws -> [Guest] {
        do {
            let dto = try await guestListDataSource.getGuestList(request: .init())
            // TODO: dto 명세후 매핑 로직 작성
            return dummyGuests
        }
        catch {
            return dummyGuests
        }
    }
}

private extension GuestListWorker {
    var dummyGuests: [Guest] {
        [
            .init(
                user: .init(
                    name: "박건우",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 21,
                    address: "서울시 금천구",
                    pictures: ["https://img.sbs.co.kr/newsnet/etv/upload/2021/03/05/30000673929_1280.jpg"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    name: "이재용",
                    gender: .male,
                    career: "학생",
                    birth: .init(),
                    age: 25,
                    address: "포항항",
                    pictures: ["https://i.pinimg.com/originals/2c/2c/60/2c2c60b20cb817a80afd381ae23dab05.jpg"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    name: "박재민",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 25,
                    address: "비공개",
                    pictures: ["https://img.theqoo.net/img/fzxPW.jpg"],
                    answers: [],
                    keyword: []
                ),
                isLiked: true
            ),
            .init(
                user: .init(
                    name: "강진호",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 30,
                    address: "비공개",
                    pictures: ["https://post-phinf.pstatic.net/MjAxOTAyMTZfMTMz/MDAxNTUwMjg0NTQ3Njk3.nOALV-TOkthnpIEg3kFCA6QA221DrLgZsBJxMKE1Hj0g.I_EYQvpkiwhl8Jj9sTBfNIs5U7Hai968vAqa5BJHlpAg.JPEG/n1233.jpg?type=w1200"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            )
        ]
    }
}
