//
//  GuestListInteractor.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models

protocol GuestListBusinessLogic {
    func fetchGuests()
}

protocol GuestListDataStore {
    var selectedGuest: Guest? { get set }
}

class GuestListInteractor: GuestListBusinessLogic, GuestListDataStore
{
    var presenter: GuestListPresentationLogic?
    var worker: GuestListWorkerProtocol?
    
    var selectedGuest: Guest?
    
    // MARK: Business Logic
    
    func fetchGuests() {
        
    }
}
