//
//  MeetingListRouter.swift
//  
//
//  Created by 박건우 on 2022/08/06.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MeetingListRoutingProtocol
import GuestListScene
import AuthCodeScene

public final class MeetingListRouter: MeetingListRoutingLogic, MeetingListDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: MeetingListDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    public func routeToGuestListScene() {
        guard let dataStore = dataStore else {
            return
        }
        let destinationVC = GuestListViewController()
        destinationVC.router?.dataStore?.meetingId = dataStore.selectedMeetingId
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    public func routeToAuthCodeScene() {
        let destinationVC = AuthCodeViewController()
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}
