//
//  MyInteractor.swift
//  
//
//  Created by Gunoo on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MyRoutingProtocol
import Models

protocol MyBusinessLogic {}

final class MyInteractor: MyBusinessLogic, MyDataStore {
    var presenter: MyPresentationLogic?
    var worker: MyWorkerProtocol?
    
    init(worker: MyWorkerProtocol = MyWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic
    
    
}
