//
//  LikeRequestRouter.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import LikeRequestRoutingProtocol
import LikeRequestCompleteScene

public class LikeRequestRouter: NSObject, LikeRequestRoutingLogic, LikeRequestDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: LikeRequestDataStore?
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    public func routeToLikeRequestCompleteScene() {
        let vc = LikeRequestCompleteViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
