//
//  SplashRouter.swift
//  
//
//  Created by Woody on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SplashRoutingProtocol
import MeetingListScene
import LoginScene

public final class SplashRouter: SplashRoutingLogic, SplashDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: SplashDataStore?

    private var window: UIWindow? {
        if let scene = UIApplication.shared.connectedScenes.first as? UIWindowScene {
            return scene.windows.first
        }
        return nil
    }
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }

    public func routeToLoginViewController() {
        let loginViewController = LoginViewController()
        let navigationController = UINavigationController(rootViewController: loginViewController)
        navigationController.isNavigationBarHidden = true
        UIView.transition(
            with: self.window!,
            duration: 0.2,
            options: .transitionCrossDissolve,
            animations: {
                self.window?.rootViewController = navigationController
            }, completion: nil)
    }

    public func routeToMeetingListViewController() {
        let meetingListViewController = MeetingListViewController()
        let navigationController = UINavigationController(rootViewController: meetingListViewController)
        navigationController.isNavigationBarHidden = true
        UIView.transition(
            with: self.window!,
            duration: 0.2,
            options: .transitionCrossDissolve,
            animations: {
                self.window?.rootViewController = navigationController
            }, completion: nil)
    }
}
