//
//  LoginModels.swift
//  Login
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Models
import UIKit

enum Login {

    // MARK: Use cases

    enum FetchUser {
        struct Response {
            let user: User
        }
    }

    enum LoginError: Error {
        case parsing
        case appleLoginError
        case loginDataSourceError
        case noUser
    }
}
