//
//  LikeRequestCompletePresenter.swift
//  
//
//  Created by 박건우 on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikeRequestCompletePresentationLogic {
    func presentMyName(response: LikeRequestComplete.FetchMyName.Response)
}

final class LikeRequestCompletePresenter: LikeRequestCompletePresentationLogic {
    weak var viewController: LikeRequestCompleteDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentMyName(response: LikeRequestComplete.FetchMyName.Response) {
        viewController?.displayMyName(viewModel: LikeRequestComplete.FetchMyName.ViewModel(name: response.name))
    }
}
