//
//  GuestDetailRouter.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GuestDetailRoutingProtocol
import LikeRequestScene

public final class GuestDetailRouter: GuestDetailRoutingLogic, GuestDetailDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: GuestDetailDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }

    public func routeToLikeRequestScene(targetId id: Int) {
        guard let dataStore = dataStore,
              let guest = dataStore.targetGuest else {
            return
        }

        let destinationVC = LikeRequestViewController()
        destinationVC.router?.dataStore?.weddingId = dataStore.meetingID
        destinationVC.router?.dataStore?.targetGuest = guest
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }

    public func routeToMeetingListScene() {
        viewController?.navigationController?.popToRootViewController(animated: true)
    }
    
    public func routeToLoginScene() {
        NotificationCenter.default.post(name: Notification.Name("LogoutNotification"), object: nil)
    }
}
