//
//  GuestDetailRouter.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GuestDetailRoutingProtocol

public final class GuestDetailRouter: GuestDetailRoutingLogic, GuestDetailDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: GuestDetailDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
