//
//  ProfileRegisterPresenter.swift
//  ProfileRegister
//
//  Created by Yoojin Park on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileRegisterPresentationLogic
{
  func presentSomething(response: ProfileRegister.Something.Response)
}

class ProfileRegisterPresenter: ProfileRegisterPresentationLogic
{
  weak var viewController: ProfileRegisterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProfileRegister.Something.Response)
  {
    let viewModel = ProfileRegister.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
