//
//  ProfileRegisterRouter.swift
//  ProfileRegister
//
//  Created by Yoojin Park on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import ProfileRegisterCompleteScene

@objc public protocol ProfileRegisterRoutingLogic {
    func routeToRegisterComplete()
}

public protocol ProfileRegisterDataPassing {
    var dataStore: ProfileRegisterDataStore? { get set }
}

public class ProfileRegisterRouter: NSObject, ProfileRegisterRoutingLogic, ProfileRegisterDataPassing {
    weak var viewController: ProfileRegisterViewController?
    public var dataStore: ProfileRegisterDataStore?

    // MARK: Routing

    public func routeToRegisterComplete() {
        let destinationController = ProfileRegisterCompleteViewController()
        self.viewController?.navigationController?.setViewControllers([destinationController], animated: true)
    }

}
