//
//  ProfileRegisterWorker.swift
//  ProfileRegister
//
//  Created by Yoojin Park on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import DataSource
import Models

protocol ProfileRegisterWorkerProtocol {
    func fetchKeywords() async throws -> [Keyword]
    func fetchQuestions() async throws -> [Answer]
    func registerProfile() async throws -> Void
}

class ProfileRegisterWorker: ProfileRegisterWorkerProtocol {
    private let keywordListDataSource: KeywordListDataSourceProtocol

    init(
        _ keywordListDataSource: KeywordListDataSourceProtocol = KeywordListDataSource()
    ) {
        self.keywordListDataSource = keywordListDataSource
    }

    func fetchKeywords() async throws -> [Keyword] {
        print("fetchKeywords")
        let keywords = try await self.keywordListDataSource.getKeywords(request: GetKeywordsRequest())
        guard let data = keywords.data else { return [] }
        let keyowrds = data.map { Keyword(id: $0.keywordID, keyword: $0.keyword) }
        return keyowrds
    }

    func fetchQuestions() async throws -> [Answer] {
        return []
    }

    func registerProfile() async throws -> Void {
        return
    }

}

extension ProfileRegisterWorker {
    var dummyKeywords: [Keyword] {
        [
//            .init(keyword: "매혹적인", keywordId: <#T##String#>)
//            .init(keyword: 1, keywordId: "매혹적인"),
//            .init(keywordID: 2, keyword: "열정적인"),
//            .init(keywordID: 3, keyword: "귀여운"),
        ]
    }
}
