//
//  MyGuestListViewController.swift
//  
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DesignSystem
import SnapKit
import MyGuestListRoutingProtocol
import MyGuestListRouter

protocol MyGuestListDisplayLogic: AnyObject {}

public final class MyGuestListViewController: UIViewController, MyGuestListDisplayLogic {
    var interactor: MyGuestListBusinessLogic?
    public var router: (MyGuestListRoutingLogic & MyGuestListDataPassing)?
    
    // MARK: Object lifecycle
    
    public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MyGuestListInteractor()
        let presenter = MyGuestListPresenter()
        let router = MyGuestListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: UI

    private let navigationView: UIView = {
        let v = UIView()
        return v
    }()

    private lazy var backButton: UIImageView = {
        let v = UIImageView()
        v.image = .create(.ic_arrow_back)
        v.isUserInteractionEnabled = true
        v.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(didTapBackButton)))
        return v
    }()

    private let myLikeButton: UIButton = {
        $0.setTitleColor(Pallete.Light.grey800.color, for: .normal)
        return $0
    }(UIButton(type: .system))

    // MARK: View lifecycle
    
    public override func viewDidLoad() {
        super.viewDidLoad()
        setUI()
    }

    private func setUI() {
        self.view.backgroundColor = Pallete.Light.background.color
        self.view.addSubview(self.navigationView)
        self.navigationView.addSubview(self.backButton)
        self.navigationView.snp.makeConstraints { make in
            make.top.equalTo(self.view.safeAreaLayoutGuide)
            make.leading.trailing.equalToSuperview()
            make.height.equalTo(56)
        }
        self.backButton.snp.makeConstraints { make in
            make.centerY.equalToSuperview()
            make.leading.equalToSuperview().inset(20)
        }
    }
    
    // MARK: Display Logic

    @objc func didTapBackButton() {
        router?.removeFromParent()
    }
}
