//
//  MyGuestListInteractor.swift
//  
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MyGuestListRoutingProtocol
import Models

protocol MyGuestListBusinessLogic {}

final class MyGuestListInteractor: MyGuestListBusinessLogic, MyGuestListDataStore {
    var presenter: MyGuestListPresentationLogic?
    var worker: MyGuestListWorkerProtocol?
    
    init(worker: MyGuestListWorkerProtocol = MyGuestListWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic
    
    
}
