//
//  MyGuestListPresenter.swift
//  
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyGuestListPresentationLogic {
    func presentMyLikeGuests(response: MyGuestList.FetchMyLikeGuests.Response)
    func presentMatchingGuests(response: MyGuestList.FetchMatchingGuests.Response)
}

final class MyGuestListPresenter: MyGuestListPresentationLogic {
    weak var viewController: MyGuestListDisplayLogic?
    
    // MARK: Presentation Logic

    func presentMyLikeGuests(response: MyGuestList.FetchMyLikeGuests.Response) {
        self.viewController?.displayMyLikeGuests(
            viewModel: .init(
                myLikeGuestCellViewModels: response.guests
                    .map {
                        .init(myGuestCardViewModel:
                                .init(
                                    id: $0.user.id,
                                    imageUrl: $0.user.pictures[0],
                                    name: $0.user.name,
                                    age: $0.user.age,
                                    address: $0.user.address,
                                    career: $0.user.career,
                                    isLiked: $0.isLiked
                                )
                        )
                    }
            )
        )
    }

    func presentMatchingGuests(response: MyGuestList.FetchMatchingGuests.Response) {
        self.viewController?.displayMatchingGuests(
            viewModel:
                    .init(
                        matchingGuestCellViewModels: response.guests
                            .map {
                                .init(myGuestCardViewModel:
                                        .init(
                                            id: $0.user.id,
                                            imageUrl: $0.user.pictures[0],
                                            name: $0.user.name,
                                            age: $0.user.age,
                                            address: $0.user.address,
                                            career: $0.user.career,
                                            isLiked: $0.isLiked
                                        ),
                                      dialog:
                                        .init(loveMent: "그대가 찾는 사람, 바로 저입니다.")
                                )
                            }
                    )
        )
    }

}
