//
//  GuestListWorker.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models
import DataSource

protocol GuestListWorkerProtocol {
    func fetchGuests() async throws -> [Guest]
}

class GuestListWorker: GuestListWorkerProtocol {
    
    private let guestListDataSource: GuestListDataSourceProtocol
    private let userDataSource: UserDataSoureceProtocol
    
    init(guestListDataSource: GuestListDataSourceProtocol = GuestListDataSource(),
         userDataSource: UserDataSoureceProtocol = UserDataSourece()) {
        self.guestListDataSource = guestListDataSource
        self.userDataSource = userDataSource
    }
    
    func fetchGuests() async throws -> [Guest] {
        do {
            let token = userDataSource.data?.token ?? ""
            let dto = try await guestListDataSource.getGuestList(request: .init(token: token))
            guard let guestListDTO = dto.data else { return dummyGuests }
            let guestList = guestListDTO.map(Guest.init)
            return guestList
        }
        catch {
            return dummyGuests
        }
    }
}

private extension GuestListWorker {
    var dummyGuests: [Guest] {
        [
            .init(
                user: .init(
                    id: 1,
                    name: "박건우",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 21,
                    address: "서울시 금천구",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179951395-2fd37585-b2fe-4308-9fe4-1e1fd9c2006d.png",
                               "https://user-images.githubusercontent.com/56102421/179951395-2fd37585-b2fe-4308-9fe4-1e1fd9c2006d.png",
                               "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                               "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                               "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                               "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png"],
                    answers: [
                        .init(questionID: 1, answer: "생각을 정리하고 이야기"),
                        .init(questionID: 2, answer: "자주 할수록 좋아요"),
                        .init(questionID: 3, answer: "계획적인 데이트")
                    ],
                    keyword: [
                        .init(id: 1, keyword: "활동적인"),
                        .init(id: 2, keyword: "유머있는"),
                        .init(id: 3, keyword: "논리적인"),
                        .init(id: 4, keyword: "애교있는"),
                        .init(id: 5, keyword: "낙천적인")
                    ]
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    id: 2,
                    name: "이재용",
                    gender: .male,
                    career: "학생",
                    birth: .init(),
                    age: 25,
                    address: "포항항",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954387-968f7152-23dc-496c-a6d6-48f49ac39700.png",
                               "https://user-images.githubusercontent.com/56102421/179954387-968f7152-23dc-496c-a6d6-48f49ac39700.png",
                               "https://user-images.githubusercontent.com/56102421/179954387-968f7152-23dc-496c-a6d6-48f49ac39700.png"],
                    answers: [
                        .init(questionID: 1, answer: "생각을 정리하고 이야기"),
                        .init(questionID: 2, answer: "자주 할수록 좋아요"),
                        .init(questionID: 3, answer: "계획적인 데이트")
                    ],
                    keyword: [
                        .init(id: 1, keyword: "활동적인"),
                        .init(id: 2, keyword: "유머있는"),
                        .init(id: 3, keyword: "논리적인"),
                        .init(id: 4, keyword: "애교있는"),
                        .init(id: 5, keyword: "낙천적인")
                    ]
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    id: 3,
                    name: "박재민",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 25,
                    address: "비공개",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954565-010e44d2-7bf9-40de-b2af-345a3967031d.png",
                               "https://user-images.githubusercontent.com/56102421/179954565-010e44d2-7bf9-40de-b2af-345a3967031d.png"],
                    answers: [
                        .init(questionID: 1, answer: "생각을 정리하고 이야기"),
                        .init(questionID: 2, answer: "자주 할수록 좋아요"),
                        .init(questionID: 3, answer: "계획적인 데이트")
                    ],
                    keyword: [
                        .init(id: 1, keyword: "활동적인"),
                        .init(id: 2, keyword: "유머있는"),
                        .init(id: 3, keyword: "논리적인"),
                        .init(id: 4, keyword: "애교있는"),
                        .init(id: 5, keyword: "낙천적인")
                    ]
                ),
                isLiked: true
            ),
            .init(
                user: .init(
                    id: 4,
                    name: "강진호",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 30,
                    address: "비공개",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954903-b631811a-ac0c-48f2-9b1f-727e88e7cb3f.png"],
                    answers: [
                        .init(questionID: 1, answer: "생각을 정리하고 이야기"),
                        .init(questionID: 2, answer: "자주 할수록 좋아요"),
                        .init(questionID: 3, answer: "계획적인 데이트")
                    ],
                    keyword: [
                        .init(id: 1, keyword: "활동적인"),
                        .init(id: 2, keyword: "유머있는"),
                        .init(id: 3, keyword: "논리적인"),
                        .init(id: 4, keyword: "애교있는"),
                        .init(id: 5, keyword: "낙천적인")
                    ]
                    
                ),
                isLiked: false
            )
        ]
    }
}
