//
//  GuestListWorker.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models
import DataSource

protocol GuestListWorkerProtocol {
    func fetchGuests() async throws -> [Guest]
}

class GuestListWorker: GuestListWorkerProtocol {
    
    private let guestListDataSource: GuestListDataSourceProtocol
    
    init(guestListDataSource: GuestListDataSourceProtocol = GuestListDataSource()) {
        self.guestListDataSource = guestListDataSource
    }
    
    func fetchGuests() async throws -> [Guest] {
        do {
            let dto = try await guestListDataSource.getGuestList(request: .init())
            // TODO: dto 명세후 매핑 로직 작성
            return dummyGuests
        }
        catch {
            return dummyGuests
        }
    }
}

private extension GuestListWorker {
    var dummyGuests: [Guest] {
        [
            .init(
                user: .init(
                    id: 1,
                    name: "박건우",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 21,
                    address: "서울시 금천구",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    id: 2,
                    name: "이재용",
                    gender: .male,
                    career: "학생",
                    birth: .init(),
                    age: 25,
                    address: "포항항",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954387-968f7152-23dc-496c-a6d6-48f49ac39700.png"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            ),
            .init(
                user: .init(
                    id: 3,
                    name: "박재민",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 25,
                    address: "비공개",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954565-010e44d2-7bf9-40de-b2af-345a3967031d.png"],
                    answers: [],
                    keyword: []
                ),
                isLiked: true
            ),
            .init(
                user: .init(
                    id: 4,
                    name: "강진호",
                    gender: .male,
                    career: "IT회사 개발자",
                    birth: .init(),
                    age: 30,
                    address: "비공개",
                    pictures: ["https://user-images.githubusercontent.com/56102421/179954903-b631811a-ac0c-48f2-9b1f-727e88e7cb3f.png"],
                    answers: [],
                    keyword: []
                ),
                isLiked: false
            )
        ]
    }
}
