//
//  GuestListInteractor.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import GuestListRoutingProtocol
import UIKit
import Models

protocol GuestListBusinessLogic {
    func fetchGuests()
}

class GuestListInteractor: GuestListBusinessLogic, GuestListDataStore {
    var presenter: GuestListPresentationLogic?
    var worker: GuestListWorkerProtocol?
    
    init(worker: GuestListWorkerProtocol = GuestListWorker()) {
        self.worker = worker
    }
    
    var guests: [Guest] = []
    
    var meetingId: String?
    
    // MARK: Business Logic
    
    func fetchGuests() {
        guard let worker = worker else {
            return
        }
        Task {
            do {
                let guests = try await worker.fetchGuests()
                self.guests = guests
                self.presenter?.presentGuests(response: .init(guests: guests))
            }
            catch {
                // TODO: 에러처리
            }
        }
    }
}
