//
//  ProfileRegisterCompleteInteractor.swift
//  
//
//  Created by Woody on 2022/08/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import ProfileRegisterCompleteRoutingProtocol
import Models

protocol ProfileRegisterCompleteBusinessLogic {
    func fetchMyName()
}

final class ProfileRegisterCompleteInteractor: ProfileRegisterCompleteBusinessLogic, ProfileRegisterCompleteDataStore {
    var presenter: ProfileRegisterCompletePresentationLogic?
    var worker: ProfileRegisterCompleteWorkerProtocol?

    var name: String?

    init(worker: ProfileRegisterCompleteWorkerProtocol = ProfileRegisterCompleteWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic
    
    func fetchMyName() {
        guard let worker = worker else {
            return
        }
        presenter?.presentMyName(
            response: ProfileRegisterComplete.FetchMyName.Response(name: (name ?? "") + "님")
        )
    }

}
