//
//  ProfileRegisterCompletePresenter.swift
//  
//
//  Created by Woody on 2022/08/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileRegisterCompletePresentationLogic {
    func presentMyName(response: ProfileRegisterComplete.FetchMyName.Response)
}

final class ProfileRegisterCompletePresenter: ProfileRegisterCompletePresentationLogic {
    weak var viewController: ProfileRegisterCompleteDisplayLogic?
    
    func presentMyName(response: ProfileRegisterComplete.FetchMyName.Response) {
        viewController?.displayMyName(viewModel: ProfileRegisterComplete.FetchMyName.ViewModel(name: response.name))
    }
}
