//
//  AuthCodeRouter.swift
//  
//
//  Created by 박건우 on 2022/08/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AuthCodeRoutingProtocol
import GuestListScene

public final class AuthCodeRouter: AuthCodeRoutingLogic, AuthCodeDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: AuthCodeDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func routeToGuestListScene(weddingId: Int) {
        let destinationVC = GuestListViewController()
        destinationVC.router?.dataStore?.meetingId = weddingId
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
