//
//  MeetingListInteractor.swift
//  
//
//  Created by 박건우 on 2022/08/06.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MeetingListRoutingProtocol
import Models

protocol MeetingListBusinessLogic {
    func fetchMeetings()
}

final class MeetingListInteractor: MeetingListBusinessLogic, MeetingListDataStore {
    var presenter: MeetingListPresentationLogic?
    var worker: MeetingListWorkerProtocol?
    
    init(worker: MeetingListWorkerProtocol = MeetingListWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic
    
    func fetchMeetings() {
        guard let worker = worker else {
            return
        }
        Task {
            do {
                let meetings = try await worker.fetchMeetings()
                presenter?.presentMeetings(response: .init(meetings: meetings))
            }
            catch {
                
            }
        }
    }
}
