//
//  MeetingListModels.swift
//  
//
//  Created by 박건우 on 2022/08/06.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Models
import UIKit

enum MeetingList {
    
    // MARK: Use cases
    
    enum List {
        
        struct Response {
            var meetings: [Meeting]
        }
        
        struct ViewModel {
            var meetings: [MeetingCellViewModel]
        }
    }
    
    enum Select {
        
        struct Request {
            var meetingId: Int
        }
    }
}
