//
//  MeetingListWorker.swift
//  
//
//  Created by 박건우 on 2022/08/06.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models
import DataSource

protocol MeetingListWorkerProtocol {
    func fetchMeetings() async throws -> [Meeting]
}

final class MeetingListWorker: MeetingListWorkerProtocol {

    private let meetingListDataSource: MeetingListDataSourceProtocol
    private let userDataSource: UserDataSoureceProtocol

    init(meetingListDataSource: MeetingListDataSourceProtocol = MeetingListDataSource(),
         userDataSource: UserDataSoureceProtocol = UserDataSourece()) {
        self.meetingListDataSource = meetingListDataSource
        self.userDataSource = userDataSource
    }

    func fetchMeetings() async throws -> [Meeting] {
        do {
            let dto = try await meetingListDataSource.getMeetingList(request: .init())
            guard let meetingListDTO = dto.data else { return [] }
            let meetingList = meetingListDTO.map(Meeting.init)
            return meetingList
        }
        catch {
            return []
        }
    }
}
