//
//  GuestListRouter.swift
//  GuestList
//
//  Created by Gunoo on 2022/07/09.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GuestListRoutingProtocol
import LikeRequestScene
import MyGuestListScene
import GuestDetailScene

public class GuestListRouter: GuestListRoutingLogic, GuestListDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: GuestListDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func routeToLikeRequestScene(targetId id: Int) {
        guard let dataStore = dataStore,
              let guest = dataStore.guests.filter({ $0.user.id == id }).first else {
            return
        }
        let destinationVC = LikeRequestViewController()
        destinationVC.router?.dataStore?.targetGuest = guest
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }

    public func routeToMyGuestListScene() {
        guard let dataStore = dataStore else {
            return
        }
        let destinationVC = MyGuestListViewController()
        destinationVC.router?.dataStore?.meetingId = dataStore.meetingId
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }

    public func routeToGuestDetailScene(targetId id: Int) {
        guard let dataStore = dataStore,
              let guest = dataStore.guests.filter({ $0.user.id == id }).first else {
            return
        }
        let destinationVC = GuestDetailViewController(profileDetailType: .guestProfile)
        destinationVC.router?.dataStore?.targetGuest = guest
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }

    public func routeToSelf() {
        if let viewController = viewController {
            viewController.navigationController?.popToViewController(viewController, animated: true)
        }
    }
    public func routeToMyProfile() {
        guard let _ = dataStore else {
            return
        }
        let destinationVC = GuestDetailViewController(profileDetailType: .myProfile)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }

}
