//
//  MyGuestListRouter.swift
//  
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MyGuestListRoutingProtocol
import GuestDetailScene

public final class MyGuestListRouter: MyGuestListRoutingLogic, MyGuestListDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: MyGuestListDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }

    public func routeToGuestDetailscene(targetId id: Int) {
        guard let dataStore = dataStore,
              let guest = (dataStore.matchingGuests.map({ $0.guest }) + dataStore.myLikeGuests).filter({ $0.user.id == id }).first else {
            return
        }
        let destinationVC = GuestDetailViewController()
        destinationVC.router?.dataStore?.targetGuest = guest
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}
