//
//  LikeRequestWorker.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DataSource

protocol LikeRequestWorkerProtocol {
    func getMyName() -> String
    func requestLike(message: String, receiverProfileId: Int, weddingId: Int) async throws
}

class LikeRequestWorker: LikeRequestWorkerProtocol {

    let userLocalDataSource: UserLocalDataSoureceProtocol
    let likeDataSource: LikeDataSourceProtocol
    
    init(
        userLocalDataSource: UserLocalDataSoureceProtocol = UserLocalDataSourece(),
        likeDataSource: LikeDataSourceProtocol = LikeDataSource()
    ) {
        self.userLocalDataSource = userLocalDataSource
        self.likeDataSource = likeDataSource
    }
    
    func getMyName() -> String {
        guard let user = userLocalDataSource.read(key: .localUser) else {
            return ""
        }
        return user.name
    }
    
    func requestLike(message: String, receiverProfileId: Int, weddingId: Int) async throws {
        let senderProfileId = userLocalDataSource.read(key: .localUser)?.id ?? 0
        let request = PostLikeRequest(
            body: .init(
                message: message,
                receiverProfileId: receiverProfileId,
                senderProfileId: senderProfileId,
                weddingId: weddingId
            )
        )
        do {
            _ = try await likeDataSource.postLike(request: request)
        }
        catch {
            throw error
        }
        
    }
}
