//
//  LikeRequestModels.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LikeRequest
{
    enum FetchIntroduceContents {
        struct Response {
            var userName: String
        }
        
        struct ViewModel {
            var introduceContents: String
        }
    }
    
    enum RequestLike {
        struct Request {
            var message: String
        }
        
        struct Response {
            struct Error {
                var message: String
            }
        }
        
        struct ViewModel {
            struct Error {
                var message: String
            }
        }
    }
}
