//
//  LikeRequestWorker.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DataSource

protocol LikeRequestWorkerProtocol {
    func getMyName() -> String
    func requestLike(message: String, receiverProfileId: Int) async throws
}

class LikeRequestWorker: LikeRequestWorkerProtocol {
    
    let userDataSource: UserDataSoureceProtocol
    let likeDataSource: LikeDataSourceProtocol
    
    init(
        userDataSource: UserDataSoureceProtocol = UserDataSourece(),
        likeDataSource: LikeDataSourceProtocol = LikeDataSource()
    ) {
        self.userDataSource = userDataSource
        self.likeDataSource = likeDataSource
    }
    
    func getMyName() -> String {
        userDataSource.data?.user.name ?? ""
    }
    
    func requestLike(message: String, receiverProfileId: Int) async throws {
        let senderProfileId = userDataSource.data?.user.id ?? 0
        let request = PostLikeRequest(
            body: .init(
                message: message,
                receiverProfileId: receiverProfileId,
                senderProfileId: senderProfileId
            )
        )
        do {
            _ = try await likeDataSource.postLike(request: request)
        }
        catch {
            throw error
        }
        
    }
}
