//
//  LikeRequestPresenter.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikeRequestPresentationLogic {
    func presentIntroduceContents(response: LikeRequest.FetchIntroduceContents.Response)
    func presentLikeRequestSuccess()
    func presentLikeRequestError(response: LikeRequest.RequestLike.Response.Error)
}

class LikeRequestPresenter: LikeRequestPresentationLogic
{
    weak var viewController: LikeRequestDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentIntroduceContents(response: LikeRequest.FetchIntroduceContents.Response) {
        self.viewController?.displayIntroduceContents(viewModel: .init(
            introduceContents: "\(response.userName)님의 마음을\n한 줄로 전달해보세요!"
        ))
    }
    
    func presentLikeRequestSuccess() {
        self.viewController?.displayLikeRequestSuccess()
    }
    
    func presentLikeRequestError(response: LikeRequest.RequestLike.Response.Error) {
        self.viewController?.displayLikeRequestError(viewModel: LikeRequest.RequestLike.ViewModel.Error(message: response.message))
    }
}
