//
//  LikeRequestWorker.swift
//  LikeRequest
//
//  Created by Gunoo on 2022/07/16.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikeRequestWorkerProtocol {
    func getMyName() -> String
}

class LikeRequestWorker: LikeRequestWorkerProtocol {
    func getMyName() -> String {
        "박우인"
    }
}
