//
//  LikeRequestCompleteRouter.swift
//  
//
//  Created by 박건우 on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import LikeRequestCompleteRoutingProtocol

public final class LikeRequestCompleteRouter: LikeRequestCompleteRoutingLogic, LikeRequestCompleteDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: LikeRequestCompleteDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    public func routeToGuestListScene() {
        viewController?.navigationController?.popViewControllers(viewsTo: 1)
    }

    public func routeToMyGuestListScene() {
        NotificationCenter.default.post(name: .init("routeToMyGuestListSceneFromLikeRequestCompleteScene"), object: nil)
        viewController?.navigationController?.popViewControllers(viewsTo: 1)
    }
}

extension UINavigationController {
    func popViewControllers(viewsTo: Int, animated: Bool = true) {
       if viewControllers.count > viewsTo {
         let vc = viewControllers[viewsTo]
         popToViewController(vc, animated: animated)
       }
     }
}

