//
//  SplashPresenter.swift
//  
//
//  Created by Woody on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentLogin()
    func presentMeetingList()
}

final class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
    
    // MARK: Do something
    func presentLogin() {
        viewController?.displayLogin()
    }

    func presentMeetingList() {
        viewController?.displayMeetingList()
    }
}
