//
//  SplashModels.swift
//  
//
//  Created by Woody on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Models
import UIKit

enum Splash {
    
    // MARK: Use cases
    
    enum Somthing {
        struct Reuqest {}
        
        struct Response {}
        
        struct ViewModel {}
    }
}
