//
//  SplashWorker.swift
//  
//
//  Created by Woody on 2022/08/23.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Models
import DataSource

protocol SplashWorkerProtocol {
    func judgeIsUserLocallyExisted() -> Bool
    func judgeIsTokenLocallyExisted() -> Bool
}

final class SplashWorker: SplashWorkerProtocol {
    private let userLocalDataSource: UserLocalDataSoureceProtocol

    init(_ userLocalDataSource: UserLocalDataSoureceProtocol = UserLocalDataSourece()) {
        self.userLocalDataSource = userLocalDataSource
    }

    func judgeIsUserLocallyExisted() -> Bool {
        if userLocalDataSource.read(key: .localUser) != nil {
            return true
        }
        return false
    }

    func judgeIsTokenLocallyExisted() -> Bool {
        if userLocalDataSource.readToken(key: .token) != nil {
            print(userLocalDataSource.readToken(key: .token))
            return true
        }
        return false
    }
}
