//
//  LoginInteractor.swift
//  Login
//
//  Created by Woody on 2022/07/17.
//  Copyright (c) 2022 kr.mash-up. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Models

protocol LoginBusinessLogic {
    func appleLogin()
}

protocol LoginDataStore {
    var user: User? { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    
    var user: User?
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    var appleLoginManager: AppleLoginManager?
    
    func appleLogin() {
        worker = LoginWorker()
        worker?.doneLogin = { [weak self] in
            self?.presenter?.presentLogin()
        }
        
        worker?.failLogin = { [weak self] in
            self?.presenter?.failLogin()
        }
        
        Task {
            worker?.appleLogin()
        }
        
    }
}
