//
//  AuthCodePresenter.swift
//  
//
//  Created by 박건우 on 2022/08/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthCodePresentationLogic {
    func presentWeddingCodeSuccess(response: AuthCode.RequestWeddingCode.Response.Success)
    func presentWeddingCodeError(response: AuthCode.RequestWeddingCode.Response.Error)
}

final class AuthCodePresenter: AuthCodePresentationLogic {
    weak var viewController: AuthCodeDisplayLogic?
    
    // MARK: Do something
    
    func presentWeddingCodeSuccess(response: AuthCode.RequestWeddingCode.Response.Success) {
        viewController?.displayWeddingCodeSuccess(viewModel: .init(weddingId: response.weddingId))
    }
    
    func presentWeddingCodeError(response: AuthCode.RequestWeddingCode.Response.Error) {
        viewController?.displayWeddingCodeError(viewModel: .init(message: response.message))
    }
}
