//
//  AuthCodeModels.swift
//  
//
//  Created by 박건우 on 2022/08/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Models
import UIKit

enum AuthCode {
    
    // MARK: Use cases
    
    enum RequestWeddingCode {
        struct Request {
            var weddingCode: String
        }
        
        struct Response {
            struct Success {
                var weddingId: Int
            }
            
            struct Error {
                var message: String
            }
        }
        
        struct ViewModel {
            struct Success {
                var weddingId: Int
            }
            
            struct Error {
                var message: String
            }
        }
    }
}
