//
//  ProfileRegisterCompleteRouter.swift
//  
//
//  Created by Woody on 2022/08/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ProfileRegisterCompleteRoutingProtocol

public final class ProfileRegisterCompleteRouter: ProfileRegisterCompleteRoutingLogic, ProfileRegisterCompleteDataPassing {
    public weak var viewController: UIViewController?
    public var dataStore: ProfileRegisterCompleteDataStore?
    
    public init() {}
    
    // MARK: Routing
    
    public func removeFromParent() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
