//
//  GuestDetailInteractor.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import GuestDetailRoutingProtocol
import Models

protocol GuestDetailBusinessLogic {}

final class GuestDetailInteractor: GuestDetailBusinessLogic, GuestDetailDataStore {
    var presenter: GuestDetailPresentationLogic?
    var worker: GuestDetailWorkerProtocol?
    
    init(worker: GuestDetailWorkerProtocol = GuestDetailWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic
    
    
}
