//
//  GuestDetailModels.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Models
import UIKit

enum GuestDetail {
    
    // MARK: Use cases
    
    enum GetGuest {
        struct Response {
            var guest: Guest
        }
        
        struct ViewModel {
            var guest: GuestDetailViewModel
        }
    }

    enum GetMeetingCount {
        struct Response {
            var meetings: [Meeting]
        }
        struct ViewModel {
            var isHidden: Bool
        }
    }
}
