//
//  GuestDetailPresenter.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GuestDetailPresentationLogic {
    func presentGuest(response: GuestDetail.GetGuest.Response)
}

final class GuestDetailPresenter: GuestDetailPresentationLogic {
    weak var viewController: GuestDetailDisplayLogic?
    
    // MARK: Presentation Logic

    func presentGuest(response: GuestDetail.GetGuest.Response) {
        self.viewController?.displayGuest(
            viewModel: .init(
                guest: .init(name: response.guest.user.name,
                             age: response.guest.user.age,
                             address: response.guest.user.address,
                             career: response.guest.user.career,
                             images: response.guest.user.pictures.map {
                                 UserProfileImagewCellViewModel(userProfileImageViewModel: .init(imageUrl: $0))
                             },
                             keywords: response.guest.user.keyword,
                             answers: response.guest.user.answers.map { $0.answer }
                            )
            )
        )
        
    }
}
