//
//  GuestDetailInteractor.swift
//  
//
//  Created by Woody on 2022/07/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import GuestDetailRoutingProtocol
import Models

protocol GuestDetailBusinessLogic {
    func fetchGuest()
}

final class GuestDetailInteractor: GuestDetailBusinessLogic, GuestDetailDataStore {
    var presenter: GuestDetailPresentationLogic?
    var worker: GuestDetailWorkerProtocol?

    var targetGuest: Guest?

    init(worker: GuestDetailWorkerProtocol = GuestDetailWorker()) {
        self.worker = worker
    }
    
    // MARK: Business Logic

    func fetchGuest() {
        guard let selectedGuest = targetGuest else {
            // TODO: 에러처리
            presenter?.presentGuest(response: .init(guest: dummyGuest))
            return
        }

        presenter?.presentGuest(response: .init(guest: selectedGuest))
    }
}

private extension GuestDetailInteractor {
    var dummyGuest: Guest {
        .init(
            user: .init(
                id: 1,
                name: "박건우",
                gender: .male,
                career: "IT회사 개발자",
                birth: .init(),
                age: 21,
                address: "서울시 금천구",
                pictures: ["https://user-images.githubusercontent.com/56102421/179951395-2fd37585-b2fe-4308-9fe4-1e1fd9c2006d.png",
                           "https://user-images.githubusercontent.com/56102421/179951395-2fd37585-b2fe-4308-9fe4-1e1fd9c2006d.png",
                           "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                           "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                           "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png",
                           "https://user-images.githubusercontent.com/56102421/179951845-1bc77f9d-0491-4c46-84b1-5b424d66bd60.png"],
                answers: [ "생각을 정리하고 이야기",
                           "자주 할수록 좋아요",
                           "계획적인 데이트"
                         ],
                keyword: [
                    "활동적인", "유머있는", "논리적인", "애교있는", "낙천적인"
                ]
            ),
            isLiked: false
        )
    }
}
