//
//  MyDataPassing.swift
//  
//
//  Created by Gunoo on 2022/07/17.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

public protocol MyDataPassing {
    var dataStore: MyDataStore? { get set }
}
